name: CelestialMovement
version: '${version}'
main: me.diademiemi.celestialmovement.CelestialMovement
api-version: 1.13
authors: [ diademiemi ] # Change this to your username
description: Add movement options like Celeste into Minecraft
commands:
  celestial:
    description: Turn on/off Celestial Movement
    usage: /celestial toggle
